spring:
  application:
    name: pingo_back

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: C##PINGO
    password: Asd1234!
    driver-class-name: oracle.jdbc.OracleDriver


server:
  port: 8080
  servlet:
    context-path: /pingo

mybatis:
  mapper-locations: classpath:mappers/**/*.xml