spring:
  application:
    name: pingo_back

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  datasource:
    url: jdbc:oracle:thin:@54.180.162.143:1521/XE
    username: pingo
    password: Qwer1234
    driver-class-name: oracle.jdbc.OracleDriver


server:
  port: 8080
  servlet:
    context-path: /pingo

logging:
  level:
    root: INFO
    com.pingo.mapper: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

# 파일 업로드 설정
file:
  upload:
    path: uploads/

jwt:
  issuer: animetalesshop@gmail.com
  secret: IXFv859htG2PL5Bta8r0QHwvIhRh7x5m