spring:
  application:
    name: pingo_back

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  datasource:
    url: jdbc:oracle:thin:@54.180.162.143:1521/XE
    username: pingo
    password: Qwer1234
    driver-class-name: oracle.jdbc.OracleDriver

  data:
    redis:
      host: 54.180.162.143  # AWS Redis 컨테이너 IP 주소
      port: 6379
      password: ""  # 비밀번호 설정
      timeout: 6000  # 타임아웃 (밀리초)
      lettuce:
        pool:
          max-active: 10  # 최대 연결 개수
          max-idle: 5  # 최대 유휴 연결 개수
          min-idle: 2  # 최소 유휴 연결 개수
          max-wait: 5000  # 최대 대기 시간 (밀리초)

server:
  port: 8080
  servlet:
    context-path: /pingo

logging:
  level:
    root: INFO
    com.pingo.mapper: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

# 파일 업로드 설정
file:
  upload:
    path: uploads/

jwt:
  issuer: animetalesshop@gmail.com
  secret: IXFv859htG2PL5Bta8r0QHwvIhRh7x5m