spring:
  application:
    name: pingo_back

  datasource:
    url: jdbc:oracle:thin:@54.180.162.143:1521/XE
    username: pingo
    password: Qwer1234
    driver-class-name: oracle.jdbc.OracleDriver


server:
  port: 8080
  servlet:
    context-path: /pingo

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

mybatis:
  mapper-locations: classpath:mappers/**/*.xml